### ISSUE TITLE
clause centos部署出行问题

### ISSUE THREAD

**Issue by jydatatop** [chatopera/clause#13]
部署clause服务时 
Digest: sha256:b15cf21b66c6a4e98e78aa458fa56caf43b5338b3d5710326c2666ee265a83c6
Status: Downloaded newer image for chatopera/activemq:5.14.3
Pulling intent (chatopera/intent:develop)...
 到这里又不动了，是不是没有放出来，或者咱们的访问有限制？

**Comment by Samurais** [comment]
可能是网络问题，这些docker镜像已经设置为公开访问。
您可以在 https://hub.docker.com/ 上搜索到。

**Comment by jydatatop** [comment]
谢谢，已经处理！是网速的问题，联通的网不成，电信的可以！




------------------ 原始邮件 ------------------
发件人: "Samurais"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 中午11:21
收件人: "chatopera/clause"<clause@noreply.github.com>;
抄送: "lwang"<252732890@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chatopera/clause] clause centos部署出行问题 (#13)




可能是网络问题，这些docker镜像已经设置为公开访问。
 您可以在 https://hub.docker.com/ 上搜索到。
