### ISSUE TITLE
ubuntu 16.04 make 编译错误，详细内容

### ISSUE THREAD

**Issue by jydatatop** [chatopera/clause#15]
root@jydatatop-virtual-machine:/soft/clause# cmake ../..  
CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
root@jydatatop-virtual-machine:/soft/clause# make
make: *** 没有指明目标并且找不到 makefile。 停止。
root@jydatatop-virtual-machine:/soft/clause#

**Comment by Samurais** [comment]
开发环境搭建参考，https://github.com/chatopera/clause/wiki/%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA
