### ISSUE TITLE
sysdicts没有启动成功问题

### ISSUE THREAD

**Issue by haiboy1982** [chatopera/clause#22]
下载 clause-osc之后 进入admin/docker 执行   ./start.sh  
报错：**clauseosc_sysdicts_1 exited with code 132**
单独启动显示
root@075cd2541a79:/app# ./sysdicts_server "--flagfile=/config/cmd.flags"
Illegal instruction (core dumped)

导致：
clause_1    | Thrift: Mon May 11 14:37:27 2020 TSocket::open() getaddrinfo() <Host: sysdicts Port: 8066>Name or service not known
clause_1    | I0511 14:37:27.393725     1 client.cpp:47] sysdicts init exception: Could not resolve host for client socket.
clause_1    | I0511 14:37:27.393741     1 handler.cpp:120] Init fails, exception in Sysdicts.
clause_1    | F0511 14:37:27.393748     1 main.cpp:67] Check failed: handler->init() [Fatal Error] Serving Handler fails to init.
报错

通过 docker-compose ps 查看 
chatopera/sysdicts:develop   "/app/sysdicts_ser..."   About a minute ago   Restarting (132) 32 seconds ago  

redis，mq，mysql，intend 服务启动正常

Docker version 17.06.2-ce, build cec0b72

docker-compose version 1.15.0, build e12f3b9

操作系统信息：
Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Aug 22 21:09:27 UTC 2017

CentOS Linux release 7.4.1708 (Core)

gcc 信息：
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

**Comment by hailiang-wang** [comment]
参考部署文档中注意事项：

https://github.com/chatopera/clause/wiki/%E6%9C%8D%E5%8A%A1%E9%83%A8%E7%BD%B2
