### ISSUE TITLE
docker pull chatopera/sysdicts:develop拉取报错：error pulling image configuration: unknown blob

### ISSUE THREAD

**Issue by netaudio** [chatopera/clause#26]
# 描述

clause源码osc分支，提交分支:（added7dacfb6d928c7c11b242690e008bbea7da0），下面docker-compose up时候提示：
error pulling image configuration: unknown blob

## 功能

# 环境

## 操作系统

CentOS Linux release 7.6.1810 (Core) 

## 代码版本

osc分支：added7dacfb6d928c7c11b242690e008bbea7da0

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
几天之前更新的 `chatopera/sysdicts:develop`  镜像有问题，现在已经重新推送，可以下载了。

https://hub.docker.com/repository/docker/chatopera/sysdicts/tags?page=1

![image](https://user-images.githubusercontent.com/3538629/95701223-8f52a180-0c7b-11eb-8129-be5ad187de7f.png)

如果国内使用速度慢，可以配置镜像，参考部署文档：

[Docker 镜像服务](https://github.com/chatopera/clause/wiki/%E4%BE%9D%E8%B5%96%E7%8E%AF%E5%A2%83#3-%E4%BD%BF%E7%94%A8%E4%B8%AD%E5%9B%BD%E5%A4%A7%E9%99%86-dockerhub-%E9%95%9C%E5%83%8F)
