### ISSUE TITLE
如何解决停用词无法识别意图的问题？

### ISSUE THREAD

**Issue by redtree18** [chatopera/clause#28]
您好，如何实现一些礼貌用语的意图， 
比如，谢谢，你好，您好等。

说是可以修改，停用词列表，停用词配置文件在哪里，如何修改？

**Comment by hailiang-wang** [comment]
按照部署文档方式部署启动后，得到docker服务，并且有目录：

```
$PWD/var/local/data/jieba/default
```

修改里面的 stop_words.utf8。

这个修改对于新建立的机器人，有效。
