### ISSUE TITLE
开源语义理解引擎有相关api文档吗！？

### ISSUE THREAD

**Issue by redtree18** [chatopera/clause#29]
您好？

开源语义理解引擎有相关api文档吗！？
比如，语义理解有哪些接口或方法？
返回的正确 /错误代码有哪些？如rc:0, msg:train job is dispatched.
系统词典，有哪些等等？

**Comment by hailiang-wang** [comment]
API 文档参考 WIKI：https://github.com/chatopera/clause/wiki

系统词典见：https://github.com/chatopera/clause/wiki/%E7%A4%BA%E4%BE%8B%E7%A8%8B%E5%BA%8F

rc为所有 API 的返回标准，rc = 0 时，为正常返回，返回数据为 Data 类型，见 https://github.com/chatopera/clause/wiki/%E7%B3%BB%E7%BB%9F%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%AE%9E%E7%8E%B0

**Comment by hailiang-wang** [comment]
rc 不为 0 时均是异常返回，每个接口返回具体含义参考：
https://github.com/chatopera/clause/blob/osc/src/clause/src/handler.cpp

比如：

![image](https://user-images.githubusercontent.com/3538629/97130048-4f131900-177b-11eb-8970-5aaa4da83bdc.png)

![image](https://user-images.githubusercontent.com/3538629/97130067-56d2bd80-177b-11eb-88fe-5f537d956de6.png)
