### ISSUE TITLE
报错，org.apache.thrift.transport.TTransportException

### ISSUE THREAD

**Issue by redtree18** [chatopera/clause#30]
今天，输入“点外卖”进行测试时，又发生这个错误：org.apache.thrift.transport.TTransportException

**Comment by redtree18** [comment]
补充：之前，我也发生过，当时，我输入的是“厕所怎么走”。
而且，在说法里，有相应这样的句式，并成功的进行了训练；输入，“厕所在哪里“，就可以。
![image](https://user-images.githubusercontent.com/73098260/97137259-614b8200-1790-11eb-9f68-37b46c598df9.png)

**Comment by hailiang-wang** [comment]
在服务器服务 clause 目录上，执行

```
docker-compose logs -f
```

查看打印的日志信息，有无报错。

**Comment by redtree18** [comment]
![Uploading image.png…]()
这是错误的日志

**Comment by redtree18** [comment]
![Uploading image.png…]()
这是错误的日志

**Comment by redtree18** [comment]
![image](https://user-images.githubusercontent.com/73098260/97159129-5ce59000-17b5-11eb-9e30-76598866ce5a.png)
这是正确的日志

**Comment by redtree18** [comment]
clause_1    | }
clause_1    | I1026 17:57:15.529100    15 bot.cpp:310] setupNerItemSequence terms: 浣犲ソ
clause_1    | I1026 17:57:15.529115    15 bot.cpp:311] setupNerItemSequence poss: l
clause_1    | I1026 17:57:15.529140    15 bot.cpp:1014] chat labeling entities with ner model ...
clause_1    | I1026 17:57:15.529186    15 bot.cpp:1017] chat labels: B-@l
clause_1    | I1026 17:57:15.529202    15 bot.cpp:1018] chat tokens: 浣犲ソ
clause_1    | I1026 17:57:15.529217    15 bot.cpp:1022] chat entities candidates: 
clause_1    | I1026 17:57:15.529276    15 handler.cpp:2794] chat latest session info: 
clause_1    | id: "DD9D42670BAB19C824AFE5DA90C87F5E"
clause_1    | chatbotID: "sz-robot"
clause_1    | intent_name: "nihao"
clause_1    | uid: "java"
clause_1    | channel: "testclient"
clause_1    | branch: "dev"
clause_1    | resolved: true
clause_1    | createdate: "2020-10-26 17:57:14"
clause_1    | updatedate: "2020-10-26 17:57:14"
clause_1    | I1026 17:57:15.529757    15 handler.cpp:2842] chat response: Data {
clause_1    |   01: rc (i32) = 0,
clause_1    |   29: session (struct) = ChatSession {
clause_1    |     01: intent_name (string) = "nihao",
clause_1    |     02: chatbotID (string) = "sz-robot",
clause_1    |     03: uid (string) = "java",
clause_1    |     04: channel (string) = "testclient",
clause_1    |     05: resolved (bool) = true,
clause_1    |     06: id (string) = "DD9D42670BAB19C824AFE5DA90C87F5E",
clause_1    |     08: branch (string) = "dev",
clause_1    |     09: createdate (string) = "2020-10-26 17:57:14",
clause_1    |     10: updatedate (string) = "2020-10-26 17:57:14",
clause_1    |   },
clause_1    |   30: message (struct) = ChatMessage {
clause_1    |     07: receiver (string) = "java",
clause_1    |   },
clause_1    | } 
^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2c
这是正确的日志

**Comment by redtree18** [comment]
clause_1    | } utterance: "骀崇瑰ゅ
clause_1    | utters {
clause_1    |   id: "344E32F247BA69163791D33850DB10BB"
clause_1    |   intent_id: "48706FD72B9106CC426F7FCF703B71BB"
clause_1    |   utterance: "甯驿镐唤{vegetable}锛殄皗location}"
clause_1    | }
clause_1    | utters {
clause_1    |   id: "DE233ACBD5A57A8517BB616750CB00BB"
clause_1    |   intent_id: "48706FD72B9106CC426F7FCF703B71BB"
clause_1    |   utterance: "甯驿镐唤{vegetable}锛殄皗location}锛骁
                                                                    骀哄锋瘂phone}"
clause_1    | }
clause_1    | utters {
clause_1    |   id: "e1947de786be46feb97288377507139b"
clause_1    |   intent_id: "48706FD7"B9106CC426F7FCF703B71BB"
clause_1    | } utterance: "骅︾瑰ゅ
clause_1    | I1026 18:04:27.127197    17 bot.cpp:311] setupNerItemSequence poss: m鐅 澶?
clause_1    | I1026 18:04:27.127228    17 bot.cpp:1014] chat labeling entities with ner model ...
clause_1    | I1026 18:04:27.127310    17 bot.cpp:1017] chat labels: B-zhoubian_fujin B-@v
clause_1    | I1026 18:04:27.127355    17 bot.cpp:545] extract_slot_candidates_with_yseq append zhoubian_fujin : 绻
clause_1    | I1026 18:04:27.127375    17 bot.cpp:1022] chat entities candidates:  zhoubian_fujin 绻
clause-rt_clause_1 exited with code 139
^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2cclause_1    | I1026 18:04:29.255568     1 activemq.cpp:35] Broker URI: failover:(tcp://activemq:61616)
clause_1    | I1026 18:04:29.257014     1 activemq.cpp:51] [broker] connecting ...
clause_1    | The Connection's Transport has been Restored.
clause_1    | I1026 18:04:29.265282     1 activemq.cpp:53] [broker] connected successfully.
clause_1    | I1026 18:04:29.267311     1 subscriber.cpp:45] [subscriber] setup listener successfully.
clause_1    | I1026 18:04:29.268532     1 publisher.cpp:39] [publisher] init done.
clause_1    | I1026 18:04:29.269176     1 client.cpp:44] sysdicts init connection successfully.
clause_1    | I1026 18:04:29.273036     1 main.cpp:79] serving on port 8056
clause_1    | Thrift: Mon Oct 26 18:04:29 2020 TNonblockingServer: Serving with 1 io threads.
clause_1    | Thrift: Mon Oct 26 18:04:29 2020 TNonblockingServer: using libevent 2.1.10-stable method epoll
clause_1    | Thrift: Mon Oct 26 18:04:29 2020 TNonblocking: IO thread #0 registered for listen.
clause_1    | Thrift: Mon Oct 26 18:04:29 2020 TNonblocking: IO thread #0 registered for notify.
clause_1    | Thrift: Mon Oct 26 18:04:29 2020 TNonblockingServer: IO thread #0 entering loop...

这是错误的最后的一点日志

**Comment by hailiang-wang** [comment]
这里，`clause-rt_clause_1 exited with code 139` 代表有一个 BUG，我还不确定 BUG 的原因，
```
clause_1 | I1026 18:04:27.127375 17 bot.cpp:1022] chat entities candidates: zhoubian_fujin 绻
clause-rt_clause_1 exited with code 139
^[[?1;2c^[[?1;2c^[[?1;2c^[[?1;2cclause_1 | I1026 18:04:29.255568 1 activemq.cpp:35] Broker URI: failover:(tcp://activemq:61616)
clause_1 | I1026 18:04:29.257014 1 activemq.cpp:51] [broker] connecting ...
```

是执行了 `chat entities candidates: zhoubian_fujin ` 后发生的。
可以帮忙分享一个可以重现该问题的 profile.json 文件吗？

类似于 https://github.com/chatopera/clause-quick-start/blob/master/profile.json

现在，不确定是使用问题还是 BUG，暂时认为是 BUG。

**Comment by redtree18** [comment]
另外，我再反应个问题：
我刚试的时候，
“这边有哪些公交”，可以
但是，“问一下这边有哪些公交”，他就不行识别不到
我说法里，也确实，只加了“这边有哪些公交”！
请问，确实是这样吗，如果这样，我要枚举的说法也太多了吧？

**Comment by redtree18** [comment]
补充刚发的这个问题：

**Comment by redtree18** [comment]
补充刚提的这个问题：
在说法有“周围有哪些公交”，“周边有哪些公交”，“这边有哪些公交”的情况下
输入“问，周围有哪些公交”，可以识别到
输入“问一下，周围有哪些公交”。可以识别
输入“请问，周围有哪些公交”，报TTransportException错误
输入“问一下这边有哪些公交”，识别不到，也没报错
输入“问一下周围有哪些公交”，可以识别
输入“问下，这边有哪些公交”，识别不到，也没报错
感觉是“这边”的问题，还是“这边有哪些公交”是后来加的原因，训练好像会有延迟？？？

**Comment by redtree18** [comment]
我查看了profile.json，确实，没有“这边有哪些公交”

**Comment by redtree18** [comment]
我查看了，profile.json，确实没有“这边有哪些公交”的说法。
这就奇怪了，我明明调了好几次train。
而且，昨天，我最后加的一个意图（附近公交）也是，怎么train也好像加不进。
但是今天一早我点了下train，就可以了。
按理说，要是train没用，那么会老是没用，不会过一天又行了。要是有用，为什么会不实时，要等一天，而且，也是这两天才发生的，以前好像没发现过？？？？
还是“develop”有滞后，和最新的训练文件夹在交互的时候，出现了问题，还是什么情况？？
希望可以给个解答。谢谢

**Comment by redtree18** [comment]
![image](https://user-images.githubusercontent.com/73098260/98193285-c43ed500-1f57-11eb-8aa6-00886040a502.png)
确实好像如此，我11点11分又点了一次，出现了一个新的文件夹。
但是develop没有更新

**Comment by hailiang-wang** [comment]
这个问题后来有什么新发现吗？
