### ISSUE TITLE
两个槽位一起填满没有区分先后的问题，比如查询票价

### ISSUE THREAD

**Issue by redtree18** [chatopera/clause#31]
查询票价时，始发站和目的站因为用的是同一个词典词槽，导致在会话时，只要输入一次车站名，就填满了两个槽位，这个怎么办？？？

**Comment by hailiang-wang** [comment]
也就是说，创建两个槽位，但是绑定的同一个词典。
解决方案：
1. 尽量多的添加说法，并且在说法中目的地和始发有明确的前后语。
2. 使用追问，不在说法中添加槽位，说法类似于“我要从香港出发”，这样“我要从上海出发”也会被识别出意图，但是因为追问的存在，会继续提问始发地。
3. 在识别到所有信息后，下单前，请用户确认，并推送表单，用户可以直接编辑表单。

**Comment by redtree18** [comment]
最好，还是，槽位要有先后顺序，否则很难实现，我们都是全语音沟通的

**Comment by redtree18** [comment]
[profile.zip](https://github.com/chatopera/clause/files/5493102/profile.zip)

**Comment by redtree18** [comment]
这个文件，会报错TTransportException得，如“请问周围有哪些公交”

**Comment by redtree18** [comment]
![image](https://user-images.githubusercontent.com/73098260/98317345-47733000-2017-11eb-9e9c-1885c2dd1668.png)
今天发生了一次，宕机！

**Comment by hailiang-wang** [comment]
新问题请创建新 Issue，并且要说明宕机原因。

**Comment by redtree18** [comment]
你们也挺忙的，先把具体的问题，解决了吧，那个报错和相同词典的两个槽位一次填槽的问题

**Comment by hailiang-wang** [comment]
使用最新的镜像解决此问题：

升级办法，修改 .env 文件，添加或更新变量 `CLAUSE_BUILD`

```
CLAUSE_BUILD=e7357d9
```


.env 文件模板：https://github.com/chatopera/clause/blob/osc/sample.env

然后执行：

```
docker-compose pull
docker-compose up -d
```

此处，```CLAUSE_BUILD=e7357d9``` 代表容器构建是基于源码 e7357d9
