### ISSUE TITLE
根据SDK请求接口，训练的时候，一直返回状态码4

### ISSUE THREAD

**Issue by zhy960324** [chatopera/clause#33]
服务器通过docker部署了服务。然后根据java sdk运行测试案例
![image](https://user-images.githubusercontent.com/23372028/103187992-8f208480-4901-11eb-8044-67247a2ff5d2.png)
一直卡在训练这里
服务器日志
![image](https://user-images.githubusercontent.com/23372028/103188004-9d6ea080-4901-11eb-8d35-ac27553eab3e.png)

请问是出了什么问题

**Comment by hailiang-wang** [comment]
1）请提供 java sdk 的源码或链接。

2）请提供更多 clause 服务的日志，尤其是如果有错误日志。

**Comment by zhy960324** [comment]
> 1）请提供 java sdk 的源码或链接。
> 
> 2）请提供更多 clause 服务的日志，尤其是如果有错误日志。

1) sdk源码链接 https://github.com/chatopera/clause-sdk-java
2）目前没有更多的报错信息。就一直输出上面的提示

**Comment by zhy960324** [comment]
![image](https://user-images.githubusercontent.com/23372028/103195818-f9dfb900-491d-11eb-98f5-7474000560db.png)
有个数据库语句错误。

目前数据库的表结构如下
![image](https://user-images.githubusercontent.com/23372028/103195876-15e35a80-491e-11eb-8675-1184c6b6e97d.png)

对应报错表cl_dicts的结构如下
![image](https://user-images.githubusercontent.com/23372028/103195984-488d5300-491e-11eb-8161-4512d5c1c0a4.png)

**Comment by hailiang-wang** [comment]
https://github.com/chatopera/clause/blob/osc/src/clause/config/sql/0.clause-setup.sql

![image](https://user-images.githubusercontent.com/3538629/103196466-38c23e80-491f-11eb-8739-af4495a4b9fc.png)

数据库初始化 SQL 中是有该字段的。

**Comment by hailiang-wang** [comment]
请提供服务部署方式。
另外，临时解决方案是将 https://github.com/chatopera/clause/blob/osc/src/clause/config/sql/0.clause-setup.sql 在 mysql 数据上执行一下。

**Comment by zhy960324** [comment]
可能是版本问题，请问 我直接下载github上的1.2.1tag 的可以吗

**Comment by hailiang-wang** [comment]
可以使用 osc 分支的最新的代码或 dist 分支。
另外，你之前那个是怎么部署的？
参考部署文档使用

https://github.com/chatopera/clause/wiki/%E6%9C%8D%E5%8A%A1%E9%83%A8%E7%BD%B2

**Comment by zhy960324** [comment]
我之前是参考gitlee上的https://gitee.com/mirrors/Clause
用docker 部署的。 我现在用1.2.1的试一下

**Comment by zhy960324** [comment]
问题解决了，谢谢
