### ISSUE TITLE
system中的001.corretto-jdk.sh和001.nodejs.sh无法安装

### ISSUE THREAD

**Issue by zhuhongwei123** [chatopera/clause#34]
001.corretto-jdk.sh中的：wget --no-check-certificate -O $JDKNAME https://static-public.chatopera.com/vendors/java/java-1.8.0-amazon-corretto-jdk_8.212.04-2_amd64.deb，会出现HTTP request sent, awaiting response... 404 Not Found。
同理，001.nodejs.sh的NODEPKG=https://nodejs.org/download/release/latest-v10.x/node-v10.22.1-linux-x64.tar.gz，也是没找到这个版本。
使得无法安装。如何处理呢

**Comment by hailiang-wang** [comment]
替换脚本中，相应安装包位置：

- java-1.8.0-amazon-corretto-jdk_8.212.04-2_amd64.deb --> 获得下载地址 https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/generic-linux-install.html
- node-v10.22.1-linux-x64.tar.gz --> 查找最新 https://nodejs.org/download/release/latest-v10.x/
