### ISSUE TITLE
python 多线程同时访问, AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by zhuhongwei123** [chatopera/clause#37]
使用python多进程调用服务器上启动的服务，session = bot.putSession，报AttributeError: 'NoneType' object has no attribute 'id'，thrift.transport.TTransport.TTransportException: TSocket read 0 bytes的错误，代码如下：
def print_time(j):
         bot = Client("xxx.xx.xxx.xxx", "xxxx")
         chatbotID = "123"
    text = "今天天气"
    print("[chat] human: %s" % text)
    session = bot.putSession(Data(session=ChatSession(chatbotID=chatbotID,
                                                      uid=f"py{j}",  
                                                      channel="testclient",  
                                                      branch="dev" 
                                                      ))).session
    resp = bot.chat(Data(session=ChatSession(id=session.id), message=ChatMessage(textMessage=text)))
    if resp.session.resolved:
        intent_name = resp.session.intent_name
        print("意图的名字是:", intent_name)
        for i in resp.session.entities:
            print("词槽的名称是：", i)
    else:
        print("[错误] 返回不符合逻辑")
    bot.destroy()

for j in range(5):
    t = threading.Thread(target=print_time, args=(j,)) 
    t.start()

**Comment by hailiang-wang** [comment]
使用示例程序进行测试：

https://github.com/chatopera/clause-quick-start

1) 配置 .env
```
cp sample.env .env
```

修改 .env，使用你的 `CL_HOST`和 `CL_PORT`

2) 运行程序
```
scripts/demo.sh
```

> 依赖 bash shell 环境

在 Windows 上使用 Git Shell，https://git-scm.com/download/win

![image](https://user-images.githubusercontent.com/3538629/113085521-8f872f00-9212-11eb-8fc6-8b7baf9bfe4a.png)

**Comment by hailiang-wang** [comment]
如果示例程序没有问题，则代表 clause 服务端没有问题，这时候就需要用你的程序和 https://github.com/chatopera/clause-quick-start/blob/master/bot.py 进行比较。

**Comment by zhuhongwei123** [comment]
单线程是没有问题的，结果也是满意的。但是如果加入了多线程同时访问服务端就会出现问题。

**Comment by hailiang-wang** [comment]
这是因为 Clause 使用的 Thrift Server 设计
https://github.com/chatopera/clause/blob/293296f4af560bfb02a736d1fc2c82589d7d322e/src/clause/main.cpp#L71

Client 和 Server 之间是一个 RPC 长连接，和 RestAPI 服务模式不同。

多线程使用解决方案：
1）增加一个 RestAPI server，将 Bot Client 代理；
2）更新 main.cpp 使用 TThreadedServer

关于那种 thrift server 更好？
请参考更多网络资料。

**Comment by hailiang-wang** [comment]
另外一个方案，将 BOT CLIENT 作为进程内 static 对象，让线程内共享。成本更低。

**Comment by zhuhongwei123** [comment]
好的，谢谢。

**Comment by zhuhongwei123** [comment]
![image](https://user-images.githubusercontent.com/34514695/113998970-2778be80-988c-11eb-8a7c-fa688149051a.png)
您好，按照您说的方法 增加一个 RestAPI server，将 Bot Client 代理。但是python 多线程，依然有问题，问题如图所示，这是日志的错误截图，这是什么问题造成的呢。谢谢

**Comment by hailiang-wang** [comment]
抱歉，我也没有遇到过这个问题，你可以看看是不是 MySQL 服务被停掉了。
作为一个开源项目，我们的支持有限，虽然一些人可以用起来，但是一些人还是需要我们的支持才能用起来，后者，我推荐使用 Chatopera 云服务。

https://bot.chatopera.com/

**Comment by zhuhongwei123** [comment]
好的谢谢
