### ISSUE TITLE
No rule to make target '../../lib/libthriftnb.so', needed by 'src/clause/clause_server'

### ISSUE THREAD

**Issue by caigao** [chatopera/clause#41]
ubuntu:~/clause/build/debug$ make

[ 32%] Building CXX object src/clause/CMakeFiles/clause_server.dir/serving/server_constants.cpp.o
[ 33%] Building CXX object src/clause/CMakeFiles/clause_server.dir/serving/server_types.cpp.o
make[2]: *** No rule to make target '../../lib/libthriftnb.so', needed by 'src/clause/clause_server'.  Stop.
CMakeFiles/Makefile2:347: recipe for target 'src/clause/CMakeFiles/clause_server.dir/all' failed
make[1]: *** [src/clause/CMakeFiles/clause_server.dir/all] Error 2
Makefile:90: recipe for target 'all' failed

环境：ubuntu 18.04，使用官方脚本并执行sudo apt-get install libevent-dev

**Comment by hailiang-wang** [comment]
脚本 https://github.com/chatopera/clause/blob/osc/admin/install-3rd/system.sh 和 https://github.com/chatopera/clause/blob/osc/admin/install-3rd/user.sh 执行的顺利吗？

都安装上了？

**Comment by hailiang-wang** [comment]
这个错误是 libthriftnb 没有安装到 https://github.com/chatopera/clause/tree/osc/lib 里。

**Comment by caigao** [comment]
./admin/install-3rd/system.sh
./admin/install-3rd/user.sh
都执行了，没发现明显错误。

**Comment by caigao** [comment]
libthriftnb 需要手动安装吗？
最后的log看thrift安装过程中并没有报错
make[2]: Leaving directory '/home/g/clause/build/thrift/thrift-0.12.0'
make[1]: Leaving directory '/home/g/clause/build/thrift/thrift-0.12.0'
+ cd /home/g/clause/cmake/user/../..
+ /home/g/clause/cmake/user/../../bin/thrift -version
Thrift version 0.12.0

但lib里面并没有libthriftnb 
ubuntu:~/clause/lib$ ls libthrift*
libthrift-0.12.0.so  libthrift.a  libthrift.la  libthrift.so  libthriftz-0.12.0.so  libthriftz.a  libthriftz.la  libthriftz.so

**Comment by hailiang-wang** [comment]
看不到完整的日志，

推测是libevent 包导致的 thriftnb lib 没有编译成功。
https://www.cnblogs.com/shihuc/p/5938656.html
![image](https://user-images.githubusercontent.com/3538629/145410226-201cf3a6-5a60-4bbd-9cec-e5ab510fda5d.png)

可以在执行一下 
```
cmake/user/002.libevent.sh
cmake/user/005.thrift.sh
```

查看一下安装的过程，有没有错误。

**Comment by hailiang-wang** [comment]
执行脚本的账号需要配置 sudo 面输入密码。
没有配置该项导致中间依赖包 libevent 安装失败，thriftnb 没有编译出来。
