### ISSUE TITLE
docker的clause_1一直尝试重连mysql，一直连接不上请问一下为什么？

### ISSUE THREAD

**Issue by jiweizhangxu** [chatopera/clause#43]
执行./start.sh效果如下：一直在重复如下报错：
![mysql](https://user-images.githubusercontent.com/88191580/182540909-af3e2a1b-689e-4d17-a11e-1395ba022fed.png)
但是去看docker里面都启动正常了：
![3 2](https://user-images.githubusercontent.com/88191580/182541047-88f9a5c8-21d7-4177-8e8c-051212b8751d.png)
此时运行bot.py会报错：
![3 3](https://user-images.githubusercontent.com/88191580/182541149-d2663a8d-e754-4418-b0f6-4abbe44978a6.png)

**Comment by hailiang-wang** [comment]
本代码库不再升级，所有的对智能对话机器人的支持将通过 [Chatopera 云服务](https://docs.chatopera.com/) 提供，面向企业和开发者使用，资费或私有部署，查看[文档](https://docs.chatopera.com/products/chatbot-platform/contract/index.html)。
